import {
  IProduct,
  IOrder,
  ILicense,
  IUser,
  IAdminOverviewStats,
  ProductCategory,
  ProductStatus,
  OrderStatus,
  PaymentMethod,
  LicenseStatus,
  UserRole,
  UserStatus,
} from '@tudongnro/shared-types';

export const MOCK_PRODUCTS: IProduct[] = [
  {
    id: 'prod_1',
    name: 'Auto NRO Pro Ultimate',
    slug: 'auto-nro-pro-ultimate',
    tagline: 'Phần mềm toàn diện tối ưu hóa tự động hóa mọi hoạt động NRO Online',
    description: `Auto NRO Pro Ultimate là bộ công cụ đỉnh cao dành cho game thủ Ngọc Rồng Online. Tích hợp AI điều khiển nhân vật thông minh, tự động né quái siêu cấp, hỗ trợ đập đồ lên cấp 8-9 an toàn, tự động làm chuỗi nhiệm vụ từ Sơ sinh đến Tương lai và Võ đài liên vũ trụ.
    
    Phần mềm hoạt động ngầm, không chiếm chuột bàn phím, tương thích mượt mà với MicroEmulator và các bản mod Java/PC hiện hành.`,
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    ],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    category: ProductCategory.ALL_IN_ONE,
    status: ProductStatus.ACTIVE,
    currentVersion: 'v4.8.2',
    changelog: [
      {
        version: 'v4.8.2',
        releaseDate: '2026-09-15',
        notes: [
          'Tối ưu thuật toán tự động nhặt ngọc rồng sao rơi',
          'Sửa lỗi mất kết nối khi chuyển khu vực Thần Điện',
          'Thêm tính năng tự động dùng bùa khi hết thời gian',
        ],
      },
      {
        version: 'v4.8.0',
        releaseDate: '2026-08-28',
        notes: [
          'Hỗ trợ đập đồ thông minh chống nổ sao pha lê',
          'Giảm 40% dung lượng RAM tiêu thụ trên mỗi tab',
        ],
      },
    ],
    features: [
      {
        title: 'Auto Đập Đồ Thông Minh',
        description: 'Thuật toán canh nhịp mili-giây, tự ngừng khi xịt liên tiếp, bảo vệ ngọc và đá may mắn.',
      },
      {
        title: 'Auto Làm Nhiệm Vụ 1-Click',
        description: 'Tự động vượt qua chuỗi nhiệm vụ Khỉ đen, Tàu Pảy Pảy, Fide, Xên bọ hung thần tốc.',
      },
      {
        title: 'Chống Phát Hiện & Không Chiếm Chuột',
        description: 'Mô phỏng thao tác phím người dùng ngẫu nhiên, ẩn tiến trình hệ thống tuyệt đối an toàn.',
      },
      {
        title: 'Hỗ Trợ Treo Nhiều Tab',
        description: 'Quản lý tập trung 20-50 tài khoản cùng lúc với bảng điều khiển trực quan.',
      },
    ],
    plans: [
      {
        planId: 'plan_7d',
        name: 'Gói 7 Ngày Trải Nghiệm',
        durationDays: 7,
        price: 50000,
        originalPrice: 70000,
      },
      {
        planId: 'plan_30d',
        name: 'Gói 30 Ngày Phổ Biến',
        durationDays: 30,
        price: 150000,
        originalPrice: 200000,
        isPopular: true,
      },
      {
        planId: 'plan_90d',
        name: 'Gói 90 Ngày Tiết Kiệm',
        durationDays: 90,
        price: 380000,
        originalPrice: 500000,
      },
      {
        planId: 'plan_permanent',
        name: 'Gói Trọn Đời (Lifetime)',
        durationDays: 0,
        price: 850000,
        originalPrice: 1200000,
      },
    ],
    systemRequirements: {
      os: 'Windows 10 / 11 (64-bit)',
      ram: 'Tối thiểu 4GB RAM (Khuyến nghị 8GB cho 10+ tab)',
      notes: 'Cài đặt sẵn Java 8 hoặc Java 17, tắt Antivirus trước khi giải nén lần đầu.',
    },
    terms: 'Bản quyền cấp cho 01 máy tính vật lý (HWID). Hỗ trợ đổi máy 1 lần/tháng miễn phí.',
    salesCount: 1420,
    viewCount: 18900,
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-09-15T00:00:00.000Z',
  },
  {
    id: 'prod_2',
    name: 'Auto Săn Boss VIP Siêu Tốc',
    slug: 'auto-san-boss-vip',
    tagline: 'Đón đầu Boss xuất hiện, tự bay khu, combo skill dứt điểm đoạt bảo vật',
    description: `Công cụ chuyên biệt dành cho bang hội và cày cuốc Boss Fide, Cooler, Android 13-20, Black Goku, Broly. Hệ thống radar quét dữ liệu máy chủ theo thời gian thực (realtime radar), lập tức đưa nhân vật đến khu vực có Boss chỉ trong 0.2 giây.`,
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    ],
    category: ProductCategory.SAN_BOSS,
    status: ProductStatus.ACTIVE,
    currentVersion: 'v3.2.0',
    changelog: [
      {
        version: 'v3.2.0',
        releaseDate: '2026-09-10',
        notes: ['Cập nhật tọa độ boss mới ở Hành tinh Ngục Tù', 'Tối ưu tốc độ dịch chuyển tức thời'],
      },
    ],
    features: [
      {
        title: 'Radar Radar Boss Realtime',
        description: 'Báo trước Boss xuất hiện trên toàn map với khoảng cách mili-giây.',
      },
      {
        title: 'Auto Dịch Chuyển Khu Vực',
        description: 'Tự động nhảy khu vắng, giữ slot và kích hoạt combo chiêu dứt điểm.',
      },
      {
        title: 'Auto Nhặt Đồ Rơi',
        description: 'Ưu tiên nhặt cải trang, găng trang bị thần linh, đồ kích hoạt trước đối thủ.',
      },
    ],
    plans: [
      {
        planId: 'boss_7d',
        name: 'Gói 7 Ngày',
        durationDays: 7,
        price: 40000,
        originalPrice: 60000,
      },
      {
        planId: 'boss_30d',
        name: 'Gói 30 Ngày',
        durationDays: 30,
        price: 120000,
        originalPrice: 180000,
        isPopular: true,
      },
      {
        planId: 'boss_permanent',
        name: 'Gói Vĩnh Viễn',
        durationDays: 0,
        price: 650000,
        originalPrice: 900000,
      },
    ],
    systemRequirements: {
      os: 'Windows 10 / 11 (64-bit)',
      ram: '2GB RAM trở lên',
    },
    terms: 'Nghiêm cấm chia sẻ license cho người khác. Hệ thống sẽ tự khóa nếu phát hiện trùng HWID.',
    salesCount: 890,
    viewCount: 12400,
    createdAt: '2026-02-14T00:00:00.000Z',
    updatedAt: '2026-09-10T00:00:00.000Z',
  },
  {
    id: 'prod_3',
    name: 'Auto Úp Đệ Tử & Treo Đậu 24/7',
    slug: 'auto-up-de-tu-treo-dau',
    tagline: 'Cày tiềm năng đệ tử thần tốc, tự thu hoạch đậu thần và hồi sinh đệ tử',
    description: `Giải pháp hoàn hảo để xây dựng những chiến binh đệ tử max chỉ số. Tự động bơm đậu khi đệ tụt HP/KI, tự né người chơi phá đám, tự tìm bãi quái phù hợp sức mạnh hiện tại, tự động xin đậu bang hội và thu hoạch đậu theo chu kỳ.`,
    thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    ],
    category: ProductCategory.AUTO_TRAIN,
    status: ProductStatus.ACTIVE,
    currentVersion: 'v2.5.1',
    changelog: [
      {
        version: 'v2.5.1',
        releaseDate: '2026-09-01',
        notes: ['Thêm tùy chọn ưu tiên chỉ số Tấn Công/HP cho đệ tử', 'Tối ưu tự động về nhà khi hết đậu'],
      },
    ],
    features: [
      {
        title: 'Tự Động Nuôi Đệ Tử',
        description: 'Tối ưu hóa thời gian mở skill 2, skill 3, skill 4 tỉ lệ đẹp nhất.',
      },
      {
        title: 'Treo Máy Bền Bỉ 24/7',
        description: 'Cơ chế tự đăng nhập lại khi mất kết nối mạng (Auto Reconnect).',
      },
    ],
    plans: [
      {
        planId: 'train_7d',
        name: 'Gói 7 Ngày',
        durationDays: 7,
        price: 30000,
        originalPrice: 45000,
      },
      {
        planId: 'train_30d',
        name: 'Gói 30 Ngày',
        durationDays: 30,
        price: 90000,
        originalPrice: 140000,
        isPopular: true,
      },
      {
        planId: 'train_90d',
        name: 'Gói 90 Ngày',
        durationDays: 90,
        price: 220000,
        originalPrice: 320000,
      },
    ],
    systemRequirements: {
      os: 'Windows 7 / 8 / 10 / 11',
      ram: '2GB RAM',
    },
    terms: 'Key dùng độc quyền cho 01 tài khoản máy.',
    salesCount: 1650,
    viewCount: 24100,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'prod_4',
    name: 'Bản Mod Tiện Ích & Giảm RAM Multi-Tab',
    slug: 'mod-tien-ich-multi-tab',
    tagline: 'Mở 50-100 tab mượt mà trên máy cấu hình yếu, hiển thị chỉ số chuyên sâu',
    description: `Bản mod can thiệp đồ họa sâu, ẩn hiệu ứng kỹ năng không cần thiết, hiển thị chính xác HP quái, khoảng cách đối thủ và tích hợp bảng phím tắt nhanh chuyển tab siêu tốc cho dân buôn và cày cuốc số lượng lớn.`,
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    galleryUrls: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    ],
    category: ProductCategory.TIEN_ICH,
    status: ProductStatus.ACTIVE,
    currentVersion: 'v5.1.0',
    changelog: [
      {
        version: 'v5.1.0',
        releaseDate: '2026-08-15',
        notes: ['Giảm thêm 30% GPU usage khi ẩn toàn bộ nhân vật trong map'],
      },
    ],
    features: [
      {
        title: 'Tối Ưu Siêu Nhẹ',
        description: 'Chỉ 35MB RAM cho mỗi tab chạy nền liên tục.',
      },
      {
        title: 'Phím Tắt Đa Năng',
        description: 'Chuyển tab tức thì, đồng bộ thao tác hàng loạt tài khoản.',
      },
    ],
    plans: [
      {
        planId: 'mod_30d',
        name: 'Gói 30 Ngày',
        durationDays: 30,
        price: 70000,
        originalPrice: 100000,
      },
      {
        planId: 'mod_permanent',
        name: 'Gói Vĩnh Viễn',
        durationDays: 0,
        price: 300000,
        originalPrice: 450000,
        isPopular: true,
      },
    ],
    systemRequirements: {
      os: 'Windows 10 / 11',
      ram: '2GB RAM',
    },
    terms: 'Hỗ trợ cập nhật bản mới trọn đời gói mua.',
    salesCount: 2100,
    viewCount: 31200,
    createdAt: '2026-01-05T00:00:00.000Z',
    updatedAt: '2026-08-15T00:00:00.000Z',
  },
];

export const MOCK_USER: IUser = {
  id: 'usr_customer_1',
  email: 'khachhang@gmail.com',
  fullName: 'Trần Văn Kiên',
  role: UserRole.CUSTOMER,
  status: UserStatus.ACTIVE,
  createdAt: '2026-03-01T10:00:00.000Z',
  updatedAt: '2026-09-18T14:20:00.000Z',
  lastLoginAt: '2026-09-20T08:30:00.000Z',
};

export const MOCK_ADMIN: IUser = {
  id: 'usr_admin_1',
  email: 'admin@tudongnrott.com',
  fullName: 'Quản Trị Viên Hệ Thống',
  role: UserRole.ADMIN,
  status: UserStatus.ACTIVE,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-09-20T10:00:00.000Z',
  lastLoginAt: '2026-09-20T12:00:00.000Z',
};

export const MOCK_ORDERS: IOrder[] = [
  {
    id: 'ord_1',
    orderCode: 'NRO-98312',
    userId: 'usr_customer_1',
    userEmail: 'khachhang@gmail.com',
    productId: 'prod_1',
    productSnapshot: {
      name: 'Auto NRO Pro Ultimate',
      slug: 'auto-nro-pro-ultimate',
      version: 'v4.8.2',
    },
    planSnapshot: {
      planId: 'plan_30d',
      name: 'Gói 30 Ngày Phổ Biến',
      durationDays: 30,
      price: 150000,
    },
    amount: 150000,
    status: OrderStatus.PAID,
    paymentMethod: PaymentMethod.VIETQR,
    paidAt: '2026-09-18T14:22:15.000Z',
    expiresAt: '2026-09-18T14:37:15.000Z',
    createdAt: '2026-09-18T14:20:00.000Z',
    updatedAt: '2026-09-18T14:22:15.000Z',
  },
  {
    id: 'ord_2',
    orderCode: 'NRO-78144',
    userId: 'usr_customer_1',
    userEmail: 'khachhang@gmail.com',
    productId: 'prod_2',
    productSnapshot: {
      name: 'Auto Săn Boss VIP Siêu Tốc',
      slug: 'auto-san-boss-vip',
      version: 'v3.2.0',
    },
    planSnapshot: {
      planId: 'boss_7d',
      name: 'Gói 7 Ngày',
      durationDays: 7,
      price: 40000,
    },
    amount: 40000,
    status: OrderStatus.PAID,
    paymentMethod: PaymentMethod.VIETQR,
    paidAt: '2026-09-19T09:12:00.000Z',
    expiresAt: '2026-09-19T09:27:00.000Z',
    createdAt: '2026-09-19T09:10:00.000Z',
    updatedAt: '2026-09-19T09:12:00.000Z',
  },
  {
    id: 'ord_3',
    orderCode: 'NRO-55201',
    userId: 'usr_customer_1',
    userEmail: 'khachhang@gmail.com',
    productId: 'prod_4',
    productSnapshot: {
      name: 'Bản Mod Tiện Ích & Giảm RAM Multi-Tab',
      slug: 'mod-tien-ich-multi-tab',
      version: 'v5.1.0',
    },
    planSnapshot: {
      planId: 'mod_permanent',
      name: 'Gói Vĩnh Viễn',
      durationDays: 0,
      price: 300000,
    },
    amount: 300000,
    status: OrderStatus.PENDING,
    paymentMethod: PaymentMethod.VIETQR,
    expiresAt: '2026-09-20T13:15:00.000Z',
    createdAt: '2026-09-20T13:00:00.000Z',
    updatedAt: '2026-09-20T13:00:00.000Z',
  },
];

export const MOCK_LICENSES: ILicense[] = [
  {
    id: 'lic_1',
    licenseKey: 'NRO-8K2A-99F1-XP77-2026',
    userId: 'usr_customer_1',
    productId: 'prod_1',
    orderId: 'ord_1',
    productName: 'Auto NRO Pro Ultimate',
    productSlug: 'auto-nro-pro-ultimate',
    status: LicenseStatus.ACTIVE,
    maxDevices: 1,
    boundDevices: [
      {
        hwid: 'BFEBFBFF000906EA-MSI-MAG-Z690',
        deviceName: 'DESKTOP-KIEN-GAMING',
        activatedAt: '2026-09-18T14:25:00.000Z',
        lastActiveAt: '2026-09-20T11:45:00.000Z',
      },
    ],
    startDate: '2026-09-18T14:22:15.000Z',
    expiresDate: '2026-10-18T14:22:15.000Z',
    durationDays: 30,
    createdAt: '2026-09-18T14:22:15.000Z',
    updatedAt: '2026-09-20T11:45:00.000Z',
  },
  {
    id: 'lic_2',
    licenseKey: 'NRO-BOSS-772A-VVIP-2026',
    userId: 'usr_customer_1',
    productId: 'prod_2',
    orderId: 'ord_2',
    productName: 'Auto Săn Boss VIP Siêu Tốc',
    productSlug: 'auto-san-boss-vip',
    status: LicenseStatus.ACTIVE,
    maxDevices: 1,
    boundDevices: [
      {
        hwid: 'BFEBFBFF000906EA-MSI-MAG-Z690',
        deviceName: 'DESKTOP-KIEN-GAMING',
        activatedAt: '2026-09-19T09:15:00.000Z',
        lastActiveAt: '2026-09-20T10:10:00.000Z',
      },
    ],
    startDate: '2026-09-19T09:12:00.000Z',
    expiresDate: '2026-09-26T09:12:00.000Z',
    durationDays: 7,
    createdAt: '2026-09-19T09:12:00.000Z',
    updatedAt: '2026-09-20T10:10:00.000Z',
  },
  {
    id: 'lic_old_expired',
    licenseKey: 'NRO-TRAIN-0012-EXPD-2025',
    userId: 'usr_customer_1',
    productId: 'prod_3',
    orderId: 'ord_old_0',
    productName: 'Auto Úp Đệ Tử & Treo Đậu 24/7',
    productSlug: 'auto-up-de-tu-treo-dau',
    status: LicenseStatus.EXPIRED,
    maxDevices: 1,
    boundDevices: [],
    startDate: '2026-08-01T00:00:00.000Z',
    expiresDate: '2026-08-31T00:00:00.000Z',
    durationDays: 30,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-31T00:00:00.000Z',
  },
];

export const MOCK_ADMIN_STATS: IAdminOverviewStats = {
  totalRevenue: 124500000,
  monthlyRevenue: 28400000,
  todayRevenue: 2150000,
  totalOrders: 1840,
  pendingOrders: 12,
  activeLicenses: 986,
  totalUsers: 2450,
  newUsersToday: 38,
};
